#
# Makefile for the touchscreen drivers.
#

fts-y	+= \
	fts_main.o \
	fts_proc.o \
	ftsCompensation.o \
	ftsCore.o \
	ftsError.o \
	ftsFrame.o \
	ftsIO.o \
	ftsTest.o \
	ftsTime.o \
	ftsTool.o \
	ftsFlash.o \
	ftsGesture.o
obj-$(CONFIG_TOUCHSCREEN_ST_FTS_V521)	+= fts.o

